name: Run Telegram Bot every 5 minutes

on:
  workflow_dispatch:       # manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Get Chrome version and install matching ChromeDriver
        run: |
          # Get major.minor.build, e.g. 114.0.5735
          CHROME_VERSION_FULL=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          echo "Chrome version detected: $CHROME_VERSION_FULL"

          # Get latest matching ChromeDriver patch version
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION_FULL")

          # Fallback to latest stable if exact version not found
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
              echo "No exact ChromeDriver for $CHROME_VERSION_FULL, using latest stable"
              CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          fi

          echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"

          wget -N https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium python-telegram-bot==20.3

      - name: Run Telegram bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          NUMBER1: ${{ secrets.NUMBER1 }}
          NUMBER2: ${{ secrets.NUMBER2 }}
        run: |
          python your_bot_script.py
