name: Run Telegram Selenium Bot

on:
  workflow_dispatch:  # manual trigger, you can run it on demand

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Chrome, ChromeDriver and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2 unzip xvfb libxi6 libgconf-2-4 libnss3 libxss1 libappindicator1 libindicator7 fonts-liberation
          
          # Install Chrome stable
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          # Get matching chromedriver version
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip -o chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          rm chromedriver_linux64.zip

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium python-telegram-bot --quiet

      - name: Run Telegram bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          NUMBER1: ${{ secrets.NUMBER1 }}
          NUMBER2: ${{ secrets.NUMBER2 }}
        run: |
          # Run the bot script in background and keep alive for 10 minutes
          python bot.py &
          sleep 600
