name: Run Telegram Bot

on:
  push:
    branches: [main]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🧱 Install fixed Chrome & ChromeDriver versions
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl

          # Install Chrome 114.0.5735.133
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.133-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_114.0.5735.133-1_amd64.deb
          google-chrome --version

          # Install ChromeDriver 114.0.5735.90
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install Python dependencies
        run: pip install -r requirements.txt

      - name: 🤖 Run Telegram Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          NUMBER1: ${{ secrets.NUMBER1 }}
          NUMBER2: ${{ secrets.NUMBER2 }}
        run: python bot.py
