name: Run Telegram Bot

on:
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes, adjust if needed

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      NUMBER1: ${{ secrets.NUMBER1 }}
      NUMBER2: ${{ secrets.NUMBER2 }}

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo apt-get install -y fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 xdg-utils wget
          python -m pip install --upgrade pip
          pip install selenium python-telegram-bot requests

      - name: Run bot
        run: python index.py
